<!Doctype html>
<html>
    <head>
    </head>
    <body>
        <ul>
            <?php foreach ($meetings->getMeeting() as $meeting): /** @var $meeting Meeting\Meeting */ ?>
                <li>
                    <?= $meetings->getTitle() ?>
                    <ul>
                        <?php foreach ($meeting->getUser() as $user): ?>
                            <li><?= $user ?></li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endforeach; ?>
        </ul>
    </body>
</html>
